import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { LockKeyhole, LogOut, Package, RefreshCw, Save, Trash2, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabaseAuth, supabaseConfigured, supabaseRest, setSupabaseAccessToken } from "@/lib/supabase";

export const Route = createFileRoute("/admin")({
  head: () => ({ meta: [{ title: "Administration | OROTRONIX" }, { name: "robots", content: "noindex,nofollow" }] }),
  component: AdminPage,
});

type Product = { id:string; name:string; slug:string; brand:string|null; category_id:string|null; price:number; old_price:number|null; image_url:string|null; short_description:string|null; description:string|null; highlights:string[]; in_stock:boolean; featured:boolean };
type Category = { id:string; slug:string; name:string; description:string|null; image_url:string|null; sort_order:number };
type Repair = { id:string; slug:string; name:string; description:string|null; price_from:number; duration:string|null; active:boolean; sort_order:number };
type Order = { id:string; reference:string; customer_name:string; phone:string; total:number; status:string; created_at:string; notes:string|null };
type Settings = { id:string; store_name:string; whatsapp:string; phone:string; address:string; hours:string; banner:string|null };

const emptyProduct: Omit<Product,"id"> = { name:"",slug:"",brand:"",category_id:null,price:0,old_price:null,image_url:"",short_description:"",description:"",highlights:[],in_stock:true,featured:false };
const emptyRepair: Omit<Repair,"id"> = { name:"",slug:"",description:"",price_from:0,duration:"",active:true,sort_order:0 };

function AdminPage() {
  const [token,setToken]=useState<string|null>(() => typeof window !== "undefined" ? sessionStorage.getItem("orotronix_admin_token") : null);
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  const [tab,setTab]=useState("products");
  const [products,setProducts]=useState<Product[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [repairs,setRepairs]=useState<Repair[]>([]); const [orders,setOrders]=useState<Order[]>([]);
  const [settings,setSettings]=useState<Settings|null>(null); const [editing,setEditing]=useState<Omit<Product,"id"> & {id?:string}>(emptyProduct);
  const [editingRepair,setEditingRepair]=useState<Omit<Repair,"id"> & {id?:string}>(emptyRepair);
  const [message,setMessage]=useState("");

  const load=async()=>{ setLoading(true); setError(""); try {
    const [p,c,r,o,s]=await Promise.all([
      supabaseRest<Product[]>("products",{query:"?select=*&order=created_at.desc"}),
      supabaseRest<Category[]>("categories",{query:"?select=*&order=sort_order.asc"}),
      supabaseRest<Repair[]>("repair_services",{query:"?select=*&order=sort_order.asc"}),
      supabaseRest<Order[]>("orders",{query:"?select=id,reference,customer_name,phone,total,status,created_at,notes&order=created_at.desc&limit=50"}),
      supabaseRest<Settings[]>("store_settings",{query:"?select=*&limit=1"})
    ]);
    setProducts(p); setCategories(c); setRepairs(r); setOrders(o); setSettings(s[0] ?? null);
  } catch(e){setError(e instanceof Error?e.message:"Erreur de chargement");} finally{setLoading(false);} };

  useEffect(()=>{if(token){setSupabaseAccessToken(token);void load();}},[token]);
  const login=async(e:React.FormEvent)=>{e.preventDefault();setError("");try{const d=await supabaseAuth("token?grant_type=password",{email,password});sessionStorage.setItem("orotronix_admin_token",d.access_token);setSupabaseAccessToken(d.access_token);setToken(d.access_token);}catch(e){setError(e instanceof Error?e.message:"Connexion impossible");}};
  const logout=()=>{sessionStorage.removeItem("orotronix_admin_token");setSupabaseAccessToken(null);setToken(null);};

  if(!supabaseConfigured)return <Shell><Panel><h1 className="font-display text-2xl font-semibold">Administration OROTRONIX</h1><p className="mt-3 text-sm text-muted-foreground">Ajoutez VITE_SUPABASE_URL et VITE_SUPABASE_ANON_KEY dans Cloudflare Pages.</p><Link className="mt-6 inline-block text-sm text-gold" to="/">← Retour au site</Link></Panel></Shell>;
  if(!token)return <Shell><form onSubmit={login} className="mx-auto w-full max-w-md rounded-2xl border border-border bg-card p-7"><div className="flex h-11 w-11 items-center justify-center rounded-lg border border-gold/30 text-gold"><LockKeyhole className="h-5 w-5"/></div><h1 className="mt-5 font-display text-2xl font-semibold">Espace administration</h1><p className="mt-2 text-sm text-muted-foreground">Connectez-vous avec votre compte Supabase autorisé.</p><div className="mt-6 space-y-4"><div><Label>Email</Label><Input className="mt-2 bg-surface" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div><Label>Mot de passe</Label><Input className="mt-2 bg-surface" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div></div>{error&&<p className="mt-4 text-sm text-destructive">{error}</p>}<Button className="mt-6 w-full" type="submit">Se connecter</Button><Link className="mt-5 block text-center text-xs text-muted-foreground" to="/">Retour au site</Link></form></Shell>;

  const saveProduct=async(e:React.FormEvent)=>{e.preventDefault();setError("");setMessage("");try{const body={...editing,price:Number(editing.price),old_price:editing.old_price===null||editing.old_price===""?null:Number(editing.old_price),highlights:Array.isArray(editing.highlights)?editing.highlights:[]};if(editing.id)await supabaseRest("products",{method:"PATCH",query:"?id=eq."+editing.id,body,prefer:"return=minimal"});else await supabaseRest("products",{method:"POST",body,prefer:"return=minimal"});setEditing(emptyProduct);setMessage("Produit enregistré.");await load();}catch(e){setError(e instanceof Error?e.message:"Erreur d’enregistrement");}};
  const deleteProduct=async(id:string)=>{if(!confirm("Supprimer ce produit ?"))return;try{await supabaseRest("products",{method:"DELETE",query:"?id=eq."+id});await load();}catch(e){setError(e instanceof Error?e.message:"Suppression impossible");}};
  const saveRepair=async(e:React.FormEvent)=>{e.preventDefault();try{const body={...editingRepair,price_from:Number(editingRepair.price_from),sort_order:Number(editingRepair.sort_order)};if(editingRepair.id)await supabaseRest("repair_services",{method:"PATCH",query:"?id=eq."+editingRepair.id,body});else await supabaseRest("repair_services",{method:"POST",body});setEditingRepair(emptyRepair);setMessage("Service enregistré.");await load();}catch(e){setError(e instanceof Error?e.message:"Erreur");}};
  const deleteRepair=async(id:string)=>{if(!confirm("Supprimer ce service ?"))return;try{await supabaseRest("repair_services",{method:"DELETE",query:"?id=eq."+id});await load();}catch(e){setError(e instanceof Error?e.message:"Suppression impossible");}};
  const updateOrder=async(id:string,status:string)=>{try{await supabaseRest("orders",{method:"PATCH",query:"?id=eq."+id,body:{status}});await load();}catch(e){setError(e instanceof Error?e.message:"Erreur");}};
  const saveSettings=async()=>{if(!settings)return;try{await supabaseRest("store_settings",{method:"PATCH",query:"?id=eq."+settings.id,body:settings});setMessage("Paramètres enregistrés.");}catch(e){setError(e instanceof Error?e.message:"Erreur");}};

  return <Shell><div className="space-y-7">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="eyebrow">OROTRONIX</p><h1 className="mt-2 font-display text-3xl font-bold">Tableau de bord</h1><p className="mt-1 text-sm text-muted-foreground">Catalogue, réparations, commandes et paramètres.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>Actualiser</Button><Button variant="outline" onClick={logout}><LogOut className="mr-2 h-4 w-4"/>Déconnexion</Button></div></header>
    {error&&<div className="rounded-lg border border-destructive/40 p-4 text-sm text-destructive">{error}</div>}{message&&<div className="rounded-lg border border-gold/30 p-4 text-sm text-gold">{message}</div>}
    <nav className="flex flex-wrap gap-2">{[["products","Produits"],["repairs","Réparations"],["orders","Commandes"],["settings","Paramètres"]].map(([id,label])=><Button key={id} variant={tab===id?"default":"outline"} onClick={()=>setTab(id)}>{label}</Button>)}</nav>
    {tab==="products"&&<section className="grid gap-6 lg:grid-cols-[1fr_420px]"><div className="rounded-2xl border border-border bg-card"><div className="border-b border-border p-5"><h2 className="font-display text-lg font-semibold">Produits ({products.length})</h2></div><div className="divide-y divide-border">{products.map(p=><div key={p.id} className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="truncate font-medium">{p.name}</p><p className="text-xs text-muted-foreground">{p.price} MAD · {p.in_stock?"En stock":"Rupture"}{p.featured?" · Vedette":""}</p></div><div className="flex shrink-0 gap-2"><Button size="sm" variant="outline" onClick={()=>setEditing({...p,highlights:p.highlights||[]})}>Modifier</Button><Button size="icon" variant="ghost" onClick={()=>void deleteProduct(p.id)}><Trash2 className="h-4 w-4"/></Button></div></div>)}</div></div><ProductForm value={editing} categories={categories} onChange={setEditing} onSubmit={saveProduct} onCancel={()=>setEditing(emptyProduct)}/></section>}
    {tab==="repairs"&&<section className="grid gap-6 lg:grid-cols-[1fr_420px]"><div className="rounded-2xl border border-border bg-card"><div className="border-b border-border p-5"><h2 className="font-display text-lg font-semibold">Services de réparation</h2></div><div className="divide-y divide-border">{repairs.map(x=><div key={x.id} className="flex items-center justify-between gap-3 p-4"><div><p className="font-medium">{x.name}</p><p className="text-xs text-muted-foreground">À partir de {x.price_from} MAD · {x.active?"Actif":"Masqué"}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setEditingRepair(x)}>Modifier</Button><Button size="icon" variant="ghost" onClick={()=>void deleteRepair(x.id)}><Trash2 className="h-4 w-4"/></Button></div></div>)}</div></div><RepairForm value={editingRepair} onChange={setEditingRepair} onSubmit={saveRepair} onCancel={()=>setEditingRepair(emptyRepair)}/></section>}
    {tab==="orders"&&<section className="rounded-2xl border border-border bg-card"><div className="border-b border-border p-5"><h2 className="font-display text-lg font-semibold">Commandes ({orders.length})</h2></div><div className="divide-y divide-border">{orders.map(o=><div key={o.id} className="grid gap-3 p-4 lg:grid-cols-[1fr_auto_auto] lg:items-center"><div><p className="font-medium">{o.reference} · {o.customer_name}</p><p className="text-xs text-muted-foreground">{o.phone} · {o.total} MAD · {new Date(o.created_at).toLocaleString("fr-MA")}</p>{o.notes&&<p className="mt-1 text-xs text-muted-foreground">{o.notes}</p>}</div><span className="text-xs text-gold">{o.status}</span><select className="h-9 rounded-md border border-border bg-surface px-3 text-sm" value={o.status} onChange={e=>void updateOrder(o.id,e.target.value)}><option value="pending_whatsapp">À confirmer</option><option value="confirmed">Confirmée</option><option value="processing">En préparation</option><option value="shipped">Expédiée</option><option value="completed">Terminée</option><option value="cancelled">Annulée</option></select></div>)}{orders.length===0&&<p className="p-5 text-sm text-muted-foreground">Aucune commande.</p>}</div></section>}
    {tab==="settings"&&settings&&<section className="max-w-2xl rounded-2xl border border-border bg-card p-6 space-y-4"><h2 className="font-display text-lg font-semibold">Paramètres de la boutique</h2><Field label="Nom" value={settings.store_name} onChange={v=>setSettings({...settings,store_name:v})}/><Field label="WhatsApp" value={settings.whatsapp} onChange={v=>setSettings({...settings,whatsapp:v})}/><Field label="Téléphone" value={settings.phone} onChange={v=>setSettings({...settings,phone:v})}/><Field label="Adresse" value={settings.address} onChange={v=>setSettings({...settings,address:v})}/><Field label="Horaires" value={settings.hours} onChange={v=>setSettings({...settings,hours:v})}/><div><Label>Banner</Label><Textarea className="mt-2 bg-surface" value={settings.banner||""} onChange={e=>setSettings({...settings,banner:e.target.value})}/></div><Button onClick={()=>void saveSettings()}><Save className="mr-2 h-4 w-4"/>Enregistrer</Button></section>}
  </div></Shell>;
}

function ProductForm({value,categories,onChange,onSubmit,onCancel}:{value:Omit<Product,"id">&{id?:string};categories:Category[];onChange:(v:any)=>void;onSubmit:(e:React.FormEvent)=>void;onCancel:()=>void}){return <form onSubmit={onSubmit} className="rounded-2xl border border-border bg-card p-6 space-y-4"><h2 className="font-display text-lg font-semibold">{value.id?"Modifier":"Nouveau"} produit</h2><Field label="Nom" value={value.name} onChange={v=>onChange({...value,name:v})}/><Field label="Slug" value={value.slug} onChange={v=>onChange({...value,slug:v})}/><Field label="Marque" value={value.brand||""} onChange={v=>onChange({...value,brand:v})}/><div><Label>Catégorie</Label><select className="mt-2 h-10 w-full rounded-md border border-border bg-surface px-3 text-sm" value={value.category_id||""} onChange={e=>onChange({...value,category_id:e.target.value||null})}><option value="">Sans catégorie</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><Field label="Prix MAD" value={String(value.price)} onChange={v=>onChange({...value,price:Number(v)||0})} type="number"/><Field label="Ancien prix" value={value.old_price==null?"":String(value.old_price)} onChange={v=>onChange({...value,old_price:v===""?null:Number(v)||0})} type="number"/></div><Field label="Image URL" value={value.image_url||""} onChange={v=>onChange({...value,image_url:v})}/><Field label="Description courte" value={value.short_description||""} onChange={v=>onChange({...value,short_description:v})}/><div><Label>Description</Label><Textarea className="mt-2 bg-surface" value={value.description||""} onChange={e=>onChange({...value,description:e.target.value})}/></div><Field label="Highlights (séparés par |)" value={value.highlights.join(" | ")} onChange={v=>onChange({...value,highlights:v.split("|").map((x:string)=>x.trim()).filter(Boolean)})}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={value.in_stock} onChange={e=>onChange({...value,in_stock:e.target.checked})}/> En stock</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={value.featured} onChange={e=>onChange({...value,featured:e.target.checked})}/> Produit vedette</label><div className="flex gap-2"><Button type="submit"><Save className="mr-2 h-4 w-4"/>Enregistrer</Button>{value.id&&<Button type="button" variant="outline" onClick={onCancel}>Annuler</Button>}</div></form>}

function RepairForm({value,onChange,onSubmit,onCancel}:{value:Omit<Repair,"id">&{id?:string};onChange:(v:any)=>void;onSubmit:(e:React.FormEvent)=>void;onCancel:()=>void}){return <form onSubmit={onSubmit} className="rounded-2xl border border-border bg-card p-6 space-y-4"><h2 className="font-display text-lg font-semibold">{value.id?"Modifier":"Nouveau"} service</h2><Field label="Nom" value={value.name} onChange={v=>onChange({...value,name:v})}/><Field label="Slug" value={value.slug} onChange={v=>onChange({...value,slug:v})}/><div><Label>Description</Label><Textarea className="mt-2 bg-surface" value={value.description||""} onChange={e=>onChange({...value,description:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><Field label="Prix à partir de" value={String(value.price_from)} onChange={v=>onChange({...value,price_from:Number(v)||0})} type="number"/><Field label="Durée" value={value.duration||""} onChange={v=>onChange({...value,duration:v})}/></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={value.active} onChange={e=>onChange({...value,active:e.target.checked})}/> Actif</label><div className="flex gap-2"><Button type="submit">Enregistrer</Button>{value.id&&<Button type="button" variant="outline" onClick={onCancel}>Annuler</Button>}</div></form>}

function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <div><Label>{label}</Label><Input className="mt-2 bg-surface" type={type} value={value} onChange={e=>onChange(e.target.value)} required/></div>}
function Shell({children}:{children:React.ReactNode}){return <div className="min-h-screen bg-background px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">{children}</div></div>}
function Panel({children}:{children:React.ReactNode}){return <div className="mx-auto max-w-xl rounded-2xl border border-gold/30 bg-card p-8">{children}</div>}
