/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ReparationRouteImport } from './routes/reparation'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as AdminRouteImport } from './routes/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparationRoute = ReparationRouteImport.update({
  id: '/reparation',
  path: '/reparation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/confirmation': typeof ConfirmationRoute
  '/panier': typeof PanierRoute
  '/reparation': typeof ReparationRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin': typeof AdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/confirmation': typeof ConfirmationRoute
  '/panier': typeof PanierRoute
  '/reparation': typeof ReparationRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin': typeof AdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/confirmation': typeof ConfirmationRoute
  '/panier': typeof PanierRoute
  '/reparation': typeof ReparationRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin': typeof AdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boutique'
    | '/commande'
    | '/confirmation'
    | '/panier'
    | '/reparation'
    | '/produit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boutique'
    | '/commande'
    | '/confirmation'
    | '/panier'
    | '/reparation'
    | '/produit/$slug'
  id:
    | '__root__'
    | '/'
    | '/boutique'
    | '/commande'
    | '/confirmation'
    | '/panier'
    | '/reparation'
    | '/produit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CommandeRoute: typeof CommandeRoute
  ConfirmationRoute: typeof ConfirmationRoute
  PanierRoute: typeof PanierRoute
  ReparationRoute: typeof ReparationRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparation': {
      id: '/reparation'
      path: '/reparation'
      fullPath: '/reparation'
      preLoaderRoute: typeof ReparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoutiqueRoute: BoutiqueRoute,
  CommandeRoute: CommandeRoute,
  ConfirmationRoute: ConfirmationRoute,
  PanierRoute: PanierRoute,
  ReparationRoute: ReparationRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  AdminRoute: AdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
